---
title: "Capstone Presentations"
editor: visual
---

# Overview

-   Students will present their work on [Capstone Presentation Day](capstone-day-2023.qmd) on 3 May 2023.

-   Presentations will follow the schedule listed [here](capstone-day-2023.qmd#schedule).

-   All slide decks must be submitted no later than Monday, May 1 at 12:00pm ET. Slides should be submitted [here](https://myuva.sharepoint.com/:f:/s/CapstoneDayMay2023/Eh4YR2Vxp8xKqUJLgQTLvJIB2K2fQNjRDgIpoks5A50Cig?e=ypMpU8).

-   Awards will be given for best presentations at the end of the day.

# About the Slide Deck

-   All student presentations will use a slide deck based on the following PowerPoint [template](resources/CapstoneSlideDeckTemplate.pptx).
-   All slide decks will be integrated into a single slide deck for presentation purposes.
-   Acknowledge clients on title slide.
-   Represent the argument of your paper in reduced form. That is, use the structure of your paper as a framework for the structure of your presentation.
-   Make sure all graphics are legible. Use the maximum space available and make sure any labels use large enough fonts to be readable by the audience.
-   If you have trouble embedding a video clip (not recommended) in PowerPoint, use a link instead.

# About the Presentation

-   Presentations will be 7 minutes long, followed by 3 minutes of questions and answers.
-   Time limits are strict --- be sure to practice your presentation as a group before presentation day.
-   There will be a timekeeper in the audience notifying you of how much time you have left.
-   During Q & A, students from the next scheduled will queue up for their talk. Details for this process will be announced on presentation day.
-   Each student should present at least 1 slide.

# Awards

Awards will be offered to capstone teams in four broad areas. 

Awards will be offered on the basis of student and audience voting at the end of the session. (Members of the audience may vote if they have participated in the entire event.) 

During the day, you are asked to take notes on each presentation relative to the categories and criteria described below.  

The categories and criteria correspond to the values and goals of data science in the broad sense to which you have been introduced in your classes and cohort experience.

The four awards are:

**&star; Most Innovative Analytical Solution**. This award will go to the project that exhibits high innovation and ingenuity in the development of a model to address their client's requirements. Criteria include appropriateness of model selection for the problem, the novelty of the model as adapted to the problem, and the performance of the model. By model, we mean the overall computational and mathematical model chosen and developed to extract meaning and value from the data. 

**&star; Most Compelling Data Visualizations**. This award will go to the paper and presentation that employs the most compelling and impactful visualizations. Criteria include the clarity and legibility of charts and graphs, the overall ability of the visualizations to translate complex information into user-interpretable form, and considerations for accessibility (e.g.color-blind friendly, vision-impaired friendly, etc.).

**&star; Most Engaging Data Story** This award will go the team who presents the most engaging data story &mdash; the narrative that best connects the problem, the data, the solution, the results, and the impact of the work done. Criteria include the clarity of language, the overall intelligibility to non-technical stakeholders, the quality of the presentation and responses to questions. 

**&star; Most Impactful Ethical Engagement** This award will go to the team whose work exhibits high ethical awareness and impact. Criteria include the degree to which ethical considerations play a part in the solution, sensitivity to limitations posed by ethical considerations, the potential impact of the work for the social good, and concern for parties affected by the problem or solution.

**Note that the criteria specified are not hard and fast &mdash; they are prompts to get you to view each project through a certain lense.**

# About the Conference

-   Students are expected to attend the entire conference.
