---
title: "DS6013 Spring 2023"
---

Welcome to the information site for DS 6013, Spring 2023. Here you will find updated information regarding the your capstone, including information about the presentation event and other things, including:
* The format of your final documents
* The format and requirements for your in-person presentation

Information about the end-of-year presentation event can be found here: [Capstone Day Information](capstone-day-2023.qmd).

# PRESENTATION + POSTER SUBMISSION

>**Sumbit by May 1, 2023 at 12:00pm ET**

Submit your Capstone Presentation Day **Slides** [here](https://myuva.sharepoint.com/:f:/s/CapstoneDayMay2023/Eh4YR2Vxp8xKqUJLgQTLvJIB2K2fQNjRDgIpoks5A50Cig?e=ypMpU8), to this folder: Folder icon Capstone Presentation Day 2023 Slides. Please use the SDS-branded `.ppt` template.

Submit your Capstone **Poster** [here](https://myuva.sharepoint.com/:f:/s/CapstoneDayMay2023/ElYEPmEmzLpGpI53KaO_BbAB0QqUS2GQo_vsMbIIo4gWLQ?e=IILq1q), to this folder: ​Folder icon Capstone Posters 2023. SDS will cover the cost of printing.

Save all files with time AND first few words of the title (examples include: “940am Chronic Disease”; “150pm Exploring Accountability”). 

You cannot edit files after the submission deadline!